cro: 1
id: service1
name: Service 1
entrypoint: service.raku
endpoints:
    - id: http
      name: HTTP (Insecure)
      protocol: http
      host-env: SERVICE1_HTTP_HOST
      port-env: SERVICE1_HTTP_PORT
ignore:
    - ignored_directory/
