cro: 1
id: service2
name: Service 2
entrypoint: service.p6
endpoints:
    - id: http
      name: HTTP (Insecure)
      protocol: http
      host-env: SERVICE2_HTTP_HOST
      port-env: SERVICE2_HTTP_PORT
